# # Tutorial básico Numpy - https://github.com/Caldeiraaf 

Numpy é um poderoso conjunto de ferramentas para executar operações matemáticas em listas de números. 
Ele funciona mais rápido que as operações comuns das listas python e também pode manipular matrizes de alta dimensão.

Como encontrar ajuda:
    
 - http://wiki.scipy.org/Tentative_NumPy_Tutorial
 - http://docs.scipy.org/doc/numpy/reference/



> O SciPy é um ecossistema baseado em Python de softwares de código aberto para matemática, ciências e engenharia.
>
>  *http://www.scipy.org/*

o NumPy é parte de um ecossistema maior de bibliotecas que se baseia no desempenho otimizado do NumPy NDArray.

Ele contém estes pacotes principais:
    
<table>
<tr>
    <td style="background:Lavender;"><img src="http://www.scipy.org/_static/images/numpylogo_med.png"  style="width:50px;height:50px;" /></td>
    <td style="background:Lavender;"><h4>NumPy</h4> Base N-dimensional array package </td>
    <td><img src="http://www.scipy.org/_static/images/scipy_med.png" style="width:50px;height:50px;" /></td>
    <td><h4>SciPy</h4> Fundamental library for scientific computing </td>
    <td><img src="http://www.scipy.org/_static/images/matplotlib_med.png" style="width:50px;height:50px;" /></td>
    <td><h4>Matplotlib</h4> Comprehensive 2D Plotting </td>
</tr>
<tr>
    <td><img src="http://www.scipy.org/_static/images/ipython.png" style="width:50px;height:50px;" /></td>
    <td><h4>IPython</h4> Enhanced Interactive Console </td>
    <td><img src="http://www.scipy.org/_static/images/sympy_logo.png" style="width:50px;height:50px;" /></td>
    <td><h4>SymPy</h4> Symbolic mathematics </td>
    <td><img src="http://www.scipy.org/_static/images/pandas_badge2.jpg" style="width:50px;height:50px;" /></td>
    <td><h4>Pandas</h4> Data structures & analysis </td>
</tr>
</table>





# Importig the library

## Import numpy library as np

Esta forma ajuda a escrever código e é quase um padrão no trabalho científico.

In [1]:
import numpy as np

## Trabalhando com  ndarray

Vamos gerar um ndarray com método np.arange

```python
np.arange([start,] stop[, step,], dtype=None)
```

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [5]:
np.arange(1,10, 3)

array([1, 4, 7])

In [6]:
np.arange(1,10, 2, dtype=np.float64)

array([1., 3., 5., 7., 9.])

## Examinando ndrray

In [7]:
ds = np.arange(1,10,2)
ds.ndim

1

In [8]:
ds.shape

(5,)

In [9]:
ds.size

5

In [10]:
ds.dtype

dtype('int64')

In [11]:
ds.itemsize

8

In [12]:
ds

array([1, 3, 5, 7, 9])

In [13]:
# Uso da memória
ds.size * ds.itemsize

40

# Por que usar numpy?

Compararemos o tempo necessário para criar duas listas e executar algumas operações básicas nelas.

### Gereando uma lista

In [21]:
%%capture timeit_results
# Regular Python
%timeit python_list_1 = range(1,1000)
python_list_1 = range(1,1000)
python_list_2 = range(1,1000)

#Numpy
%timeit numpy_list_1 = np.arange(1,1000)
numpy_list_1 = np.arange(1,1000)
numpy_list_2 = np.arange(1,1000)

In [27]:
print(timeit_results)

214 ns +- 4.78 ns per loop (mean +- std. dev. of 7 runs, 1000000 loops each)
1.42 us +- 63 ns per loop (mean +- std. dev. of 7 runs, 1000000 loops each)



### Operações básicas

In [28]:
%%capture timeit_python
%%timeit
# Regular Python
[(x + y) for x, y in zip(python_list_1, python_list_2)]
[(x - y) for x, y in zip(python_list_1, python_list_2)]
[(x * y) for x, y in zip(python_list_1, python_list_2)]
[(x / y) for x, y in zip(python_list_1, python_list_2)];

In [29]:
print(timeit_python)

281 us +- 6.09 us per loop (mean +- std. dev. of 7 runs, 1000 loops each)



In [30]:
%%capture timeit_numpy
%%timeit
#Numpy
numpy_list_1 + numpy_list_2
numpy_list_1 - numpy_list_2
numpy_list_1 * numpy_list_2
numpy_list_1 / numpy_list_2;

In [31]:
print(timeit_numpy)

6.29 us +- 307 ns per loop (mean +- std. dev. of 7 runs, 100000 loops each)



# Funções mais comuns

## Creação de lista

```python
array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
```

```python
Parameters
----------
object : array_like
    An array, any object exposing the array interface, an
    object whose __array__ method returns an array, or any
    (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then
    the type will be determined as the minimum type required
    to hold the objects in the sequence.  This argument can only
    be used to 'upcast' the array.  For downcasting, use the
    .astype(t) method.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy
    will only be made if __array__ returns a copy, if obj is a
    nested sequence, or if a copy is needed to satisfy any of the other
    requirements (`dtype`, `order`, etc.).
order : {'C', 'F', 'A'}, optional
    Specify the order of the array.  If order is 'C' (default), then the
    array will be in C-contiguous order (last-index varies the
    fastest).  If order is 'F', then the returned array
    will be in Fortran-contiguous order (first-index varies the
    fastest).  If order is 'A', then the returned array may
    be in any order (either C-, Fortran-contiguous, or even
    discontiguous).
subok : bool, optional
    If True, then sub-classes will be passed-through, otherwise
    the returned array will be forced to be a base-class array (default).
ndmin : int, optional
    Specifies the minimum number of dimensions that the resulting
    array should have.  Ones will be pre-pended to the shape as
    needed to meet this requirement.
```

In [32]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

#### Matriz (array) multidimencional

In [33]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

### Matriz de zeros e uns

```python
zeros(shape, dtype=float, order='C') and ones(shape, dtype=float, order='C')
```


```python
Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
```

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros((3,4), dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Criando vetores 

```python
np.linspace(start, stop, num=50, endpoint=True, retstep=False)
```

```python
Parameters
----------
start : scalar
    The starting value of the sequence.
stop : scalar
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
```

In [37]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [38]:
np.linspace(0,2,num=4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [39]:
np.linspace(0,2,num=4,endpoint=False)

array([0. , 0.5, 1. , 1.5])

### Criando Matriz randômica

```python
random_sample(size=None)
```

```python
Parameters
----------
size : int or tuple of ints, optional
    Defines the shape of the returned array of random floats. If None
    (the default), returns a single float.
```

In [40]:
np.random.random((2,3))

array([[0.97218317, 0.25580829, 0.5317022 ],
       [0.22221856, 0.53403561, 0.69665769]])

In [41]:
np.random.random_sample((2,3))

array([[0.06167661, 0.12263777, 0.41037003],
       [0.06058112, 0.57016929, 0.30422898]])

## Análise Estatística

In [42]:
data_set = np.random.random((2,3))
data_set

array([[0.49561617, 0.32992461, 0.52660111],
       [0.45271315, 0.27955339, 0.62870121]])

###  Calculando o maior valor

```python
np.max(a, axis=None, out=None, keepdims=False)
```

```python
Parameters
----------
a : array_like
    Input data.
axis : int, optional
    Axis along which to operate.  By default, flattened input is used.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See `doc.ufuncs` (Section "Output arguments") for more details.
keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the original `arr`.
```

In [43]:
np.max(data_set)

0.6287012115803471

In [44]:
np.max(data_set, axis=0)

array([0.49561617, 0.32992461, 0.62870121])

In [45]:
np.max(data_set, axis=1)

array([0.52660111, 0.62870121])

### Calculando o menor valor

```python
np.min(a, axis=None, out=None, keepdims=False)
```

In [46]:
np.min(data_set)

0.2795533879450368

### Calculando a média

```python
np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
```

In [47]:
np.mean(data_set)

0.4521849395063792

### Calculando a mediana

```python
np.median(a, axis=None, out=None, overwrite_input=False)
```

In [48]:
np.median(data_set)

0.47416465618240844

### Calculando o desvio padrão

```python
np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False)
```

In [49]:
np.std(data_set)

0.11784987058083893

### Calcula o somatório dos termos

```python
np.sum(a, axis=None, dtype=None, out=None, keepdims=False)
```

In [50]:
np.sum(data_set)

2.7131096370382752

## Remodelagem

```python
np.reshape(a, newshape, order='C')
```

In [51]:
np.reshape(data_set, (3,2))

array([[0.49561617, 0.32992461],
       [0.52660111, 0.45271315],
       [0.27955339, 0.62870121]])

In [52]:
np.reshape(data_set, (6,1))

array([[0.49561617],
       [0.32992461],
       [0.52660111],
       [0.45271315],
       [0.27955339],
       [0.62870121]])

In [53]:
np.reshape(data_set, (6))

array([0.49561617, 0.32992461, 0.52660111, 0.45271315, 0.27955339,
       0.62870121])

### Transforma os dados da matriz em um vetor

```python
np.ravel(a, order='C')
```

In [54]:
np.ravel(data_set)

array([0.49561617, 0.32992461, 0.52660111, 0.45271315, 0.27955339,
       0.62870121])

### Fatiamento

In [55]:
data_set = np.random.random((5,10))
data_set

array([[0.75545507, 0.09211773, 0.70170545, 0.31636944, 0.75591827,
        0.31182658, 0.05483886, 0.38306023, 0.41477905, 0.68204522],
       [0.44241304, 0.92255846, 0.91527498, 0.23172656, 0.1829566 ,
        0.25611531, 0.6178916 , 0.28830827, 0.70124998, 0.33288435],
       [0.60449442, 0.62740092, 0.30437856, 0.81039691, 0.34498345,
        0.35075329, 0.0341759 , 0.94707738, 0.27606458, 0.51447057],
       [0.8459626 , 0.65770536, 0.21239653, 0.25103245, 0.63989788,
        0.42252226, 0.46799428, 0.53535354, 0.82358364, 0.0962488 ],
       [0.79411901, 0.33637696, 0.56593269, 0.95602183, 0.70981622,
        0.3578592 , 0.75716124, 0.60389286, 0.74200115, 0.9638972 ]])

In [56]:
data_set[1]

array([0.44241304, 0.92255846, 0.91527498, 0.23172656, 0.1829566 ,
       0.25611531, 0.6178916 , 0.28830827, 0.70124998, 0.33288435])

In [57]:
data_set[1][0]

0.44241304046424934

In [58]:
data_set[1,0]

0.44241304046424934

#### Fatiando um intervalo

In [59]:
data_set[2:4]

array([[0.60449442, 0.62740092, 0.30437856, 0.81039691, 0.34498345,
        0.35075329, 0.0341759 , 0.94707738, 0.27606458, 0.51447057],
       [0.8459626 , 0.65770536, 0.21239653, 0.25103245, 0.63989788,
        0.42252226, 0.46799428, 0.53535354, 0.82358364, 0.0962488 ]])

In [60]:
data_set[2:4,0]

array([0.60449442, 0.8459626 ])

In [61]:
data_set[2:4,0:2]

array([[0.60449442, 0.62740092],
       [0.8459626 , 0.65770536]])

In [62]:
data_set[:,0]

array([0.75545507, 0.44241304, 0.60449442, 0.8459626 , 0.79411901])

#### Stepping

In [63]:
data_set[2:4:1]

array([[0.60449442, 0.62740092, 0.30437856, 0.81039691, 0.34498345,
        0.35075329, 0.0341759 , 0.94707738, 0.27606458, 0.51447057],
       [0.8459626 , 0.65770536, 0.21239653, 0.25103245, 0.63989788,
        0.42252226, 0.46799428, 0.53535354, 0.82358364, 0.0962488 ]])

In [64]:
data_set[::]

array([[0.75545507, 0.09211773, 0.70170545, 0.31636944, 0.75591827,
        0.31182658, 0.05483886, 0.38306023, 0.41477905, 0.68204522],
       [0.44241304, 0.92255846, 0.91527498, 0.23172656, 0.1829566 ,
        0.25611531, 0.6178916 , 0.28830827, 0.70124998, 0.33288435],
       [0.60449442, 0.62740092, 0.30437856, 0.81039691, 0.34498345,
        0.35075329, 0.0341759 , 0.94707738, 0.27606458, 0.51447057],
       [0.8459626 , 0.65770536, 0.21239653, 0.25103245, 0.63989788,
        0.42252226, 0.46799428, 0.53535354, 0.82358364, 0.0962488 ],
       [0.79411901, 0.33637696, 0.56593269, 0.95602183, 0.70981622,
        0.3578592 , 0.75716124, 0.60389286, 0.74200115, 0.9638972 ]])

In [65]:
data_set[::2]

array([[0.75545507, 0.09211773, 0.70170545, 0.31636944, 0.75591827,
        0.31182658, 0.05483886, 0.38306023, 0.41477905, 0.68204522],
       [0.60449442, 0.62740092, 0.30437856, 0.81039691, 0.34498345,
        0.35075329, 0.0341759 , 0.94707738, 0.27606458, 0.51447057],
       [0.79411901, 0.33637696, 0.56593269, 0.95602183, 0.70981622,
        0.3578592 , 0.75716124, 0.60389286, 0.74200115, 0.9638972 ]])

In [66]:
data_set[2:4]

array([[0.60449442, 0.62740092, 0.30437856, 0.81039691, 0.34498345,
        0.35075329, 0.0341759 , 0.94707738, 0.27606458, 0.51447057],
       [0.8459626 , 0.65770536, 0.21239653, 0.25103245, 0.63989788,
        0.42252226, 0.46799428, 0.53535354, 0.82358364, 0.0962488 ]])

In [67]:
data_set[2:4,::2]

array([[0.60449442, 0.30437856, 0.34498345, 0.0341759 , 0.27606458],
       [0.8459626 , 0.21239653, 0.63989788, 0.46799428, 0.82358364]])

## Operações básicas com matrizes

In [68]:
import numpy as np
# Matrix A 
A = np.array([[1,2],[3,4]])
# Matrix B
B = np.array([[3,4],[5,6]])

#### Adição

In [69]:
A+B

array([[ 4,  6],
       [ 8, 10]])

#### Subtração

In [70]:
A-B

array([[-2, -2],
       [-2, -2]])

#### Multiplicação (Elemento por elemento)

In [71]:
A*B

array([[ 3,  8],
       [15, 24]])

#### Multiplicação (Multiplicação de matrizes)

In [72]:
A.dot(B)

array([[13, 16],
       [29, 36]])

#### Divisão

In [73]:
A/B

array([[0.33333333, 0.5       ],
       [0.6       , 0.66666667]])

### Elevando uma matriz ao quadrado

In [74]:
np.square(A)

array([[ 1,  4],
       [ 9, 16]])

### Potenciação de uma Matriz

In [75]:
np.power(A,3) #elevando uma matriz ao cubo

array([[ 1,  8],
       [27, 64]])

### Transposta de uma matriz

In [76]:
A.transpose()

array([[1, 3],
       [2, 4]])

### Inversa de uma matriz

In [77]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])